### ISSUE TITLE
Research Orthanc features / API

### ISSUE THREAD

**Issue by brianzhouzc** [BCCF-UBCO-AD/Orthanc-TMI#35]
We need to research the API to determine which services/functions accomplish our goals, and what [if any] hidden gotchas exist.

Various services of Orthanc that seem potentially useful are below. 
The enums full names include `_OrthancPluginService_*`
- [ ] CreateJob
- [x] CreateDicom
- [x] CreateDicom2
- [ ] GetInstanceData
- [x] CreateDicomInstance
- [x] FreeDicomInstance
- [ ] ReadFile
- [x] WriteFile
- [ ] GetInstanceAdvancedJson
- [ ] DicomInstanceToJson
- [x] RegisterStorageArea
- [x] RegisterStorageArea2
- [ ] RegisterStorageCommitmentScpCallback
- [x] RegisterIncomingDicomInstanceFilter

This is just a collection of services/functions that need investigation. More tasks are needed to dig into why these might be useful, or what aspects need to be determined.

**Comment by brianzhouzc** [comment]
We also need to figure out how to retrieve the file/attachment UUID, I don't see an API for it.

**Comment by brianzhouzc** [comment]
Honestly, might be easier to implement a custom storage area. Wouldn't be hard.

**Comment by cppcooper** [comment]
> Anonymized in memory then write to disk.

Okay not so bad. We should see about removing the second write to disk from our implementation for various reasons but mostly for the sake of optimization as we already know they want this to be useful to other people as well. While we can't be accountable to random organizations and people, I think we should assume a massive scale of data is the ultimate goal.

We should move this discussion to PR #40
