### ISSUE TITLE
Link libpqxx with plugin target

### ISSUE THREAD

**Issue by brianzhouzc** [BCCF-UBCO-AD/Orthanc-TMI#37]
As title, all libraries aren't linked currently.

**Comment by cppcooper** [comment]
So the PR https://github.com/BCCF-UBCO-AD/Orthanc-TMI/pull/30 currently links fine; however the submodule dependency was removed in favor of a system package left up to the user.

We may be able to re-introduce the submodule with the latest update in the conversation I was having here https://github.com/jtv/libpqxx/pull/128#discussion_r730360778

**Comment by cppcooper** [comment]
Build system can link no problem now. The problem with libpqxx is just down to ensuring docker has it installed.. or figuring out how to install our build to a docker. (via ssh maybe? i dunno) Closing this issue.
