### ISSUE TITLE
Query database from plugin

### ISSUE THREAD

**Issue by cppcooper** [BCCF-UBCO-AD/Orthanc-TMI#48]
So our plugin needs to query the database, for at least one reason as of now. We're going to need to update md5 checksums of files which we'll be modifying. We initially went about this with libpqxx which we have two issues about:
#37 - deals previous issues linking libpqxx
#47 - deals with the plugins dependency on libpqxx and the lack thereof in the docker environment

Lately, we've talked about trying to remove the libpqxx dependency and thereby simplify deployment of this plugin. In order to remove the dependency we need something to replace it, @brianzhouzc thinks we may be able to find undocumented features of the Orthanc SDK which will allow us to perform queries on the database. [edit: This means we'll need to research a bit, which involves issue #35]

One way or another we need something that makes sense, the simpler the better.. and if the SDK can't provide what we need we will still need to figure out precisely how we want to integrate the library into the plugin.

**Comment by cppcooper** [comment]
We can potentially evade any need for direct database queries as I've commented in #35

**Comment by brianzhouzc** [comment]
Iwan is experimenting with libpqxx within the plugin now.

**Comment by brianzhouzc** [comment]
Working in [feat-phi](https://github.com/BCCF-UBCO-AD/Orthanc-TMI/tree/feat-phi) branch.
