### ISSUE TITLE
[Testing] Real world conditions

### ISSUE THREAD

**Issue by cppcooper** [BCCF-UBCO-AD/Orthanc-TMI#53]
As talked about in a previous meeting, DICOM images may come in bursts. We need to make sure that we can test this use case, and this strategy should be documented here and elsewhere (readme perhaps, or requirements.md).

edit: as underscored by the double processing issue (#92) we probably should be worried about receiving two or more files at the same time.. as the DB seems to blow up when that happens.

**Comment by brianzhouzc** [comment]
I'm going to set up a second DICOM server (either Orthanc or something more lightweight) to send DICOM files to Orthanc via the DICOM protocol. Hope this will solve the bug in #92

**Comment by cppcooper** [comment]
> I'm going to set up a second DICOM server (either Orthanc or something more lightweight) to send DICOM files to Orthanc via the DICOM protocol. Hope this will solve the bug in #92

So afaik this is done. How does it work?

**Comment by brianzhouzc** [comment]
It is done, all the changes are in feat-orthanc_client branch. I basically added a separate entry of Orthanc in Docker and configure one of them as a client. I will add more details once I merge the branch (after the mega pr)

**Comment by cppcooper** [comment]
As underscored by the double processing issue (https://github.com/BCCF-UBCO-AD/Orthanc-TMI/issues/92) we probably should be worried about receiving two or more files at the same time.. as the DB seems to blow up when that happens. So.. we really need to test that situation and confirm or reject that as a problem. If it is a problem, then my only thought is to try reverting from postgres and try with the default. If it is still a problem.. we might need two servers as part of the solution like the other team.

**Comment by cppcooper** [comment]
This too can likely be closed now with #113 (thread safety) and w/e added the second server, though we don't have any automated tests. We probably should make a script or something to run from CI so we can test that none of the containers crashed.

**Comment by cppcooper** [comment]
Leaving this open since real work conditions still need to be tested and possibly debugged.

**Comment by cppcooper** [comment]
Given we tested against several hundred local DICOM images and the project is over, gonna close this with the idea that we successfully tested enough to say this will work under real world conditions and if there are issues it won't be related to performance. Thus any issues should get separate issues.
