### ISSUE TITLE
Crosswalk table implementation

### ISSUE THREAD

**Issue by brianzhouzc** [BCCF-UBCO-AD/Orthanc-TMI#69]
Edit: Does not need crosswalk table. Orthanc table contains enough information for now.
Need table to store potential duplicate patients.

I've done a rough mockup for the crosswalk database/table structures as well as a flow chart on how to implement it.

Please change anything you see as fit.

Crosswalk tables:
```sql
CREATE TABLE dicom_instances (
    uuid VARCHAR PRIMARY KEY,
    timestamp int NOT NULL
);

CREATE TABLE dicom_identifiers (
    id INT AUTO_INCREMENT,
    uuid VARCHAR NOT NULL,
    tag_group VARCHAR NOT NULL,
    tag_element VARCHAR NOT NULL,
    value VARCHAR,
    PRIMARY KEY (id),
    FOREIGN KEY (uuid) REFERENCES dicom_instances(uuid)
);

CREATE TABLE dicom_duplicates (
    uuid VARCHAR PRIMARY KEY,
    parent_uuid VARCHAR,
    FOREIGN KEY (uuid) REFERENCES dicom_instances(uuid),
    FOREIGN KEY (parent_uuid) REFERENCES dicom_instances(uuid)
);
````
![image](https://user-images.githubusercontent.com/6280864/141854232-84372f1d-1a58-410f-9046-7441d5d7d398.png)

Rough flow diagram: https://app.creately.com/diagram/NSEROmq7LZE/edit
![image](https://user-images.githubusercontent.com/6280864/141854310-97dadece-83a6-494f-9df2-61ec61a10547.png)

**Comment by brianzhouzc** [comment]
Feel free to edit the flow diagram with the link.

**Comment by cppcooper** [comment]
Didn't want to create an account, but I'd order the long branch a bit differently.
0. On StorageCreate
1. Parse dicom data
2. Handle PHI & crosswalking
2.1 Extract PHI
2.2 Add crosswalk entry if none exists
2.3 Search for duplicates
2.4 Add crosswalk info for possible duplicates
3. Filter dicom
4. ?Add UUID tag to dicom?
5. Write to disk
6. Generate new checksum (unless the checksum is generated after the storage callback)

**Comment by brianzhouzc** [comment]
I'll update the flow chart. 
I think the table structures also needs to be changed - instead of saving all PHI per Dicom instance it's probably smart yo have a dedicated table to store patient UUID and related PHI instead. I don't know why I didnt think about this earlier

**Comment by iwanlevin** [comment]
Did we decide on a finalized version for the crosswalk tables?

**Comment by brianzhouzc** [comment]
I'll have one by the end of tomorrow

**Comment by brianzhouzc** [comment]
Close for now. Does not require corsswalk table as Orthanc's own database is sufficient.
