### ISSUE TITLE
Peer testing plans

### ISSUE THREAD

**Issue by brianzhouzc** [BCCF-UBCO-AD/Orthanc-TMI#71]
Peer testing with the other groups is happening next Friday, we need to come up with a plan on how to do it.

My suggestion is to use `feat-cstore` branch for peer testing as it is extremely simple and works fine right now. It only anonymizes incoming files and writes the anonymized copy to disk, and does not store phi anywhere. But I think even that is sufficient for a demo.

Thoughts?

**Comment by iwanlevin** [comment]
I agree and I can set up a pipeline to test the cstore branch for Friday. We could even add a simple database interaction to store phi if there is time
