### ISSUE TITLE
Plugin needs to be configurable via json

### ISSUE THREAD

**Issue by brianzhouzc** [BCCF-UBCO-AD/Orthanc-TMI#74]
We can either create our own configuration file or use Orthanc's configuration file. 
`OrthancPluginGetConfigurationPath` returns the entire Orthanc configuration file as a JSON string. We can simply parse it can read out the config we need.

**Comment by cppcooper** [comment]
I've just been adding to orthanc.json so far. The new entries haven't been documented yet, but there is an issue for that.

**Comment by brianzhouzc** [comment]
Closed. Implementing right now.

**Comment by cppcooper** [comment]
> Closed. Implementing right now.

Where?
