### ISSUE TITLE
Investigate ODBC for database communication

### ISSUE THREAD

**Issue by brianzhouzc** [BCCF-UBCO-AD/Orthanc-TMI#91]
By utilizing ODBC we can have much more flexibility with different databases. The performance cost might be a concern but seems to only be a problem when querying a large amount of data. This requires further investigation.

**Comment by brianzhouzc** [comment]
Related issue: #48

**Comment by cppcooper** [comment]
It was decided that since the planned front end requires postgres that it doesn't make sense to try and generalize the DB specs.
