### ISSUE TITLE
PHI mismatch detection

### ISSUE THREAD

**Issue by brianzhouzc** [BCCF-UBCO-AD/Orthanc-TMI#97]
According to Quinn, the conditions for mismatches are:

**Patient ID matches (Patients share the same original patient ID)**

- Case 2: +Last name, +DOB, -First name
- Case 3: +DOB, -Last name
- Case 4: -DOB
- Case 7: +First name, +Last name, +DOB, -Middle name

**Patient DOB matches (same DOB and different patientID)**

- Case 5: +DOB, +Full name, -Patient ID
- Case 6: +DOB, +Last name, -Patient ID

\+ indicates that they are the same between patients
\- Indicates that they are different between patients

It seems like it won't be too hard to implement this.

**Comment by cppcooper** [comment]
Do the +/- mean anything

**Comment by brianzhouzc** [comment]
> Do the +/- mean anything

\+ indicates that they are the same between patients
\- Indicates that they are different between patients

Forgot to add them

**Comment by cppcooper** [comment]
Well, the cases don't make sense to me entirely why each would be considered a potential mismatch.. Some seem like they'd give a lot of false positives.. like case 6 where the PID doesn't match the DOB does and the last name doesn't but also doesn't care about any other piece of information.. that'd be every single record that shares a DOB unless they happen to have the same surname.

**Comment by brianzhouzc** [comment]
> Well, the cases don't make sense to me entirely why each would be considered a potential mismatch.. Some seem like they'd give a lot of false positives.. like case 6 where the PID doesn't match the DOB does and the last name doesn't but also doesn't care about any other piece of information.. that'd be every single record that shares a DOB unless they happen to have the same surname.
> 
> edit: But yea, should be pretty easy to implement

Updated according to Quinn

**Comment by brianzhouzc** [comment]
Done
